name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - current
          - patch
          - minor
          - major
          - prerelease
      dry_run:
        description: 'Dry run (test without publishing)'
        required: false
        default: true
        type: boolean
      npm_tag:
        description: 'NPM tag for publishing'
        required: false
        default: 'latest'
        type: choice
        options:
          - latest
          - beta
          - alpha
          - next
      force_rebuild:
        description: 'Force rebuild (ignore cache)'
        required: false
        default: false
        type: boolean

jobs:
  # Verify CI status before publishing
  verify-ci:
    name: Verify CI Status
    runs-on: ubuntu-latest
    
    outputs:
      ci-success: ${{ steps.check-ci.outputs.success }}
      build-cache-key: ${{ steps.check-ci.outputs.build_cache_key }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Check CI status
      id: check-ci
      uses: actions/github-script@v7
      with:
        script: |
          // Get the latest CI run for this commit
          const { data: runs } = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'ci.yml',
            head_sha: context.sha,
            status: 'completed'
          });
          
          const latestRun = runs.workflow_runs[0];
          
          if (!latestRun) {
            core.setFailed('No CI run found for this commit. Run CI first.');
            return;
          }
          
          if (latestRun.conclusion !== 'success') {
            core.setFailed(`CI failed with status: ${latestRun.conclusion}`);
            return;
          }
          
          console.log(`✅ CI passed: ${latestRun.html_url}`);
          core.setOutput('success', 'true');
          
          // Generate build cache key for artifact reuse
          const buildCacheKey = `${{ runner.os }}-build-${{ hashFiles('src/**/*.ts', 'tsconfig.json', 'package-lock.json') }}`;
          core.setOutput('build_cache_key', buildCacheKey);

  # Quick validation and version preparation
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    needs: verify-ci
    if: needs.verify-ci.outputs.ci-success == 'true'
    
    outputs:
      current_version: ${{ steps.version.outputs.current }}
      new_version: ${{ steps.version.outputs.new }}
      final_version: ${{ steps.npm-check.outputs.final_version }}
      can_publish: ${{ steps.npm-check.outputs.can_publish }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Restore or rebuild assets
      run: |
        if [ "${{ inputs.force_rebuild }}" = "true" ]; then
          echo "🔄 Force rebuild requested"
          npm run build
        else
          # Try to restore from cache
          cache_key="${{ needs.verify-ci.outputs.build-cache-key }}"
          echo "🔍 Attempting to restore build cache: $cache_key"
          
          # If cache restore fails, rebuild
          if ! npm run build; then
            echo "⚠️ Cache miss or build failed, rebuilding..."
            npm run build
          fi
        fi
    
    - name: Calculate version
      id: version
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        
        # Calculate new version
        if [ "${{ inputs.version_type }}" = "current" ]; then
          NEW_VERSION="$CURRENT_VERSION"
          echo "📝 Keeping current version: $NEW_VERSION"
        elif [ "${{ inputs.version_type }}" = "prerelease" ]; then
          NEW_VERSION=$(npm version --no-git-tag-version prerelease --preid=beta)
          NEW_VERSION=${NEW_VERSION#v}
        else
          NEW_VERSION=$(npm version --no-git-tag-version ${{ inputs.version_type }})
          NEW_VERSION=${NEW_VERSION#v}
        fi
        
        echo "new=$NEW_VERSION" >> $GITHUB_OUTPUT
        
        echo "Version: $CURRENT_VERSION → $NEW_VERSION"
        
        # Reset package.json for validation
        git checkout package.json
    
    - name: NPM availability check and auto-increment
      id: npm-check
      run: |
        PACKAGE_NAME=$(node -p "require('./package.json').name")
        PROPOSED_VERSION="${{ steps.version.outputs.new }}"
        
        echo "🔍 Checking NPM availability for $PROPOSED_VERSION..."
        
        # Function to check if version exists
        version_exists() {
          npm view "$PACKAGE_NAME@$1" version 2>/dev/null
        }
        
        # Auto-increment logic for different version types
        if [ "${{ inputs.version_type }}" = "current" ]; then
          # For current version, just check if it exists
          if version_exists "$PROPOSED_VERSION"; then
            echo "⚠️  Version $PROPOSED_VERSION already exists on NPM"
            echo "💡 Suggestion: Use a different version type to increment"
            echo "can_publish=false" >> $GITHUB_OUTPUT
            exit 1
          else
            FINAL_VERSION="$PROPOSED_VERSION"
            echo "✅ Current version $FINAL_VERSION is available for publishing"
          fi
        elif [ "${{ inputs.version_type }}" = "prerelease" ]; then
          # For prerelease, auto-increment beta number
          BASE_VERSION=$(echo "$PROPOSED_VERSION" | sed 's/-beta\.[0-9]*$//')
          BETA_NUM=0
          
          # Find next available beta version
          while version_exists "$BASE_VERSION-beta.$BETA_NUM"; do
            echo "⚠️  Version $BASE_VERSION-beta.$BETA_NUM already exists, trying next..."
            BETA_NUM=$((BETA_NUM + 1))
          done
          
          FINAL_VERSION="$BASE_VERSION-beta.$BETA_NUM"
          echo "✅ Auto-incremented to: $FINAL_VERSION"
          
        else
          # For major/minor/patch, if exists, suggest prerelease
          if version_exists "$PROPOSED_VERSION"; then
            echo "⚠️  Version $PROPOSED_VERSION already exists"
            echo "💡 Suggestion: Use 'prerelease' version type for auto-increment"
            echo "can_publish=false" >> $GITHUB_OUTPUT
            echo "suggested_version=$PROPOSED_VERSION-beta.0" >> $GITHUB_OUTPUT
            exit 1
          else
            FINAL_VERSION="$PROPOSED_VERSION"
            echo "✅ Version $FINAL_VERSION is available"
          fi
        fi
        
        echo "can_publish=true" >> $GITHUB_OUTPUT
        echo "final_version=$FINAL_VERSION" >> $GITHUB_OUTPUT
        echo "📦 Final version to publish: $FINAL_VERSION"
    
    - name: Dry run simulation
      if: inputs.dry_run
      run: |
        echo "🚀 DRY RUN - Simulating NPM publish..."
        
        # Apply final version changes
        FINAL_VERSION="${{ steps.npm-check.outputs.final_version }}"
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "📝 Applying final version $FINAL_VERSION..."
        
        # Update package.json to final version (only if different)
        if [ "$CURRENT_VERSION" != "$FINAL_VERSION" ]; then
          npm version --no-git-tag-version "$FINAL_VERSION"
          echo "✅ Updated package.json: $CURRENT_VERSION → $FINAL_VERSION"
        else
          echo "ℹ️  Version unchanged: $FINAL_VERSION"
        fi
        
        # Update settings.ts with final version
        if [ -f "src/settings.ts" ]; then
          sed -i "s/export const VERSION = '[^']*';/export const VERSION = '$FINAL_VERSION';/" src/settings.ts
          echo "✅ Updated settings.ts VERSION constant"
        fi
        
        # Rebuild and test
        npm run build
        npm run lint
        npm run test
        
        # Simulate publish
        npm publish --dry-run --tag ${{ inputs.npm_tag }}
        
        echo "✅ Dry run completed successfully!"
    
    - name: Upload prepared assets
      if: ${{ !inputs.dry_run }}
      uses: actions/upload-artifact@v4
      with:
        name: release-assets-${{ github.sha }}
        path: |
          dist/
          src/
          package.json
          package-lock.json
        retention-days: 1

  # Actual NPM publishing
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: [verify-ci, prepare-release]
    if: ${{ !inputs.dry_run && needs.prepare-release.outputs.can_publish == 'true' }}
    
    outputs:
      published_version: ${{ steps.publish.outputs.version }}
      pr_url: ${{ steps.create-pr.outputs.pr_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Install dependencies
      run: npm ci
    
    - name: Download prepared assets
      uses: actions/download-artifact@v4
      with:
        name: release-assets-${{ github.sha }}
        path: .
    
    - name: Apply version changes
      run: |
        FINAL_VERSION="${{ needs.prepare-release.outputs.final_version }}"
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "📝 Applying final version $FINAL_VERSION..."
        
        # Update package.json to final version (only if different)
        if [ "$CURRENT_VERSION" != "$FINAL_VERSION" ]; then
          npm version --no-git-tag-version "$FINAL_VERSION"
          echo "✅ Updated package.json: $CURRENT_VERSION → $FINAL_VERSION"
        else
          echo "ℹ️  Version unchanged: $FINAL_VERSION"
        fi
        
        # Update settings.ts
        if [ -f "src/settings.ts" ]; then
          sed -i "s/export const VERSION = '[^']*';/export const VERSION = '$FINAL_VERSION';/" src/settings.ts
          echo "✅ Updated settings.ts VERSION constant"
        fi
        
        # Final rebuild
        npm run build
    
    - name: Final validation
      run: |
        echo "🔍 Final pre-publish validation..."
        
        # Quick lint and test
        npm run lint
        npm run test
        
        # Version consistency check
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        SETTINGS_VERSION=$(node -p "require('./dist/settings.js').VERSION || 'undefined'")
        
        if [ "$SETTINGS_VERSION" != "undefined" ] && [ "$PACKAGE_VERSION" != "$SETTINGS_VERSION" ]; then
          echo "❌ Version mismatch: package.json ($PACKAGE_VERSION) != settings.ts ($SETTINGS_VERSION)"
          exit 1
        fi
        
        echo "✅ Final validation passed"
    
    - name: Publish to NPM
      id: publish
      run: |
        echo "🚀 Publishing to NPM with tag: ${{ inputs.npm_tag }}"
        npm publish --tag ${{ inputs.npm_tag }}
        
        PUBLISHED_VERSION=$(node -p "require('./package.json').version")
        echo "version=$PUBLISHED_VERSION" >> $GITHUB_OUTPUT
        echo "✅ Published version $PUBLISHED_VERSION successfully!"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create release branch and PR
      id: create-pr
      run: |
        VERSION="${{ steps.publish.outputs.version }}"
        BRANCH_NAME="release/v$VERSION"
        
        # Create release branch
        git checkout -b "$BRANCH_NAME"
        git add .
        
        # Only commit if there are changes
        if git diff --cached --quiet; then
          echo "ℹ️  No changes to commit for release branch"
        else
          git commit -m "chore: release version $VERSION"
          echo "✅ Created release commit for version $VERSION"
        fi
        
        # Create and push tag
        git tag "v$VERSION"
        git push origin "v$VERSION"
        
        # Only push branch if there are commits different from main
        if git diff main --quiet; then
          echo "ℹ️  Release branch identical to main, not pushing branch"
        else
          git push origin "$BRANCH_NAME"
          echo "✅ Pushed release branch $BRANCH_NAME"
        fi
        
        # Create PR only if branch was pushed
        if git diff main --quiet; then
          echo "ℹ️  No PR needed - no changes from main branch"
          echo "pr_url=" >> $GITHUB_OUTPUT
        else
          # Create PR via GitHub API
          echo "## 📦 Release $VERSION" > pr_body.md
          echo "" >> pr_body.md
          echo "This automated PR contains the version bump and changes for release $VERSION." >> pr_body.md
          echo "" >> pr_body.md
          echo "**✅ Published to NPM:** https://www.npmjs.com/package/homebridge-echonet-lite-aircon" >> pr_body.md
          echo "**🏷️ NPM Tag:** \`${{ inputs.npm_tag }}\`" >> pr_body.md
          echo "**📋 Version Type:** \`${{ inputs.version_type }}\`" >> pr_body.md
          echo "" >> pr_body.md
          echo "### Installation" >> pr_body.md
          echo "\`\`\`bash" >> pr_body.md
          echo "npm install homebridge-echonet-lite-aircon@$VERSION" >> pr_body.md
          echo "\`\`\`" >> pr_body.md
          echo "" >> pr_body.md
          echo "### Changes" >> pr_body.md
          echo "- Version bump: ${{ needs.prepare-release.outputs.current_version }} → $VERSION" >> pr_body.md
          echo "- Updated settings.ts VERSION constant" >> pr_body.md
          echo "- Created git tag v$VERSION" >> pr_body.md
          echo "" >> pr_body.md
          echo "**Note:** This package has already been published to NPM. Merge this PR to update the main branch with the version changes." >> pr_body.md
          echo "" >> pr_body.md
          echo "🤖 Generated by NPM publish workflow" >> pr_body.md
          
          PR_URL=$(gh pr create \
            --title "chore: release version $VERSION" \
            --body-file pr_body.md \
            --base main \
            --head "$BRANCH_NAME" || echo "")
          
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
          echo "Created PR: $PR_URL"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create GitHub Release
      if: ${{ inputs.npm_tag == 'latest' }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.publish.outputs.version }}
        release_name: Release v${{ steps.publish.outputs.version }}
        body: |
          ## 🚀 Release ${{ steps.publish.outputs.version }}
          
          **NPM Package:** https://www.npmjs.com/package/homebridge-echonet-lite-aircon
          
          ### Installation
          ```bash
          npm install homebridge-echonet-lite-aircon@${{ steps.publish.outputs.version }}
          ```
          
          ### Usage with Homebridge
          Compatible with Homebridge 1.8.0+ and 2.0.0-beta.0+
          
          See [README.md](README.md) for configuration details.
        draft: false
        prerelease: ${{ contains(steps.publish.outputs.version, 'beta') || contains(steps.publish.outputs.version, 'alpha') }}

  # Cleanup and notification
  notify:
    name: Publish Notification
    runs-on: ubuntu-latest
    needs: [verify-ci, prepare-release, publish]
    if: always()
    
    steps:
    - name: Cleanup artifacts
      continue-on-error: true
      uses: actions/github-script@v7
      with:
        script: |
          // Clean up temporary artifacts
          const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          });
          
          for (const artifact of artifacts.data.artifacts) {
            if (artifact.name.includes('release-assets-')) {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
            }
          }
    
    - name: Report results
      run: |
        echo "## 📋 Publish Results"
        echo ""
        
        if [ "${{ needs.verify-ci.result }}" != "success" ]; then
          echo "❌ **CI verification failed**"
          echo "Make sure CI passes before publishing"
          exit 1
        elif [ "${{ needs.prepare-release.result }}" != "success" ]; then
          echo "❌ **Release preparation failed**"
          echo "Check the prepare-release job logs"
          exit 1
        elif [ "${{ inputs.dry_run }}" = "true" ]; then
          echo "✅ **Dry run completed successfully!**"
          echo ""
          echo "**Ready to publish:**"
          echo "- Version: ${{ needs.prepare-release.outputs.current_version }} → ${{ needs.prepare-release.outputs.final_version }}"
          echo "- NPM tag: ${{ inputs.npm_tag }}"
          echo ""
          echo "**To publish for real:**"
          echo "1. Re-run this workflow"
          echo "2. Set 'Dry run' to **false**"
          echo "3. Keep the same settings"
        elif [ "${{ needs.publish.result }}" = "success" ]; then
          echo "🎉 **Successfully published!**"
          echo ""
          echo "**Published version:** ${{ needs.publish.outputs.published_version }}"
          echo "**NPM package:** https://www.npmjs.com/package/homebridge-echonet-lite-aircon"
          echo "**Release PR:** ${{ needs.publish.outputs.pr_url }}"
          echo ""
          echo "**Next steps:**"
          echo "1. Review and merge the release PR"
          echo "2. Update documentation if needed"
        else
          echo "❌ **Publishing failed**"
          echo "Check the publish job logs for details"
          exit 1
        fi